site_name: theTowerStats

dev_addr: 127.0.0.1:8002
docs_dir: docs

repo_url: https://github.com/mahbam42/theTowerStats
repo_name: theTowerStats

nav:
  - Home: index.md
  - Phase 1: phase1.md
  - Phase 2: phase2.md
  - Phase 2.75: phase275.md
  - Project Structure: project_structure.md
  - Development: development.md
